### ISSUE TITLE
‘vector’ does not name a type; did you mean ‘Vector’

### ISSUE THREAD

**Issue by KeeganBruer** [jewettaij/superpose3d_cpp#2]
I get this error when I compile. 

/home/ros/catkin_ws/src/synchronizing_pointclouds/src/peigencalc.hpp:35:3: error: ‘vector’ does not name a type; did you mean ‘Vector’?
   35 |   vector<Scalar> evals;          // preallocated array for the eigenvalues
      |   ^~~~~~
      |   Vector

I am trying to use this inside of a ros package, but I have included all 4 .hpp files. it cant seem to find a type for the lowercase vector.

**Comment by jewettaij** [comment]
Hi Keegan
1) Which compiler are you using?  (You can usually get it to tell you the version number by passing the "--version" argument.  For example "clang++ --version")

2) Lower-case "vector" refers to std::vector, which is defined in the standard library file ("#include <vector>"), not "Vector" (which is the template argument for the PEigenCalculator template class).

I'm curious.  What happens if you replace every instance of (lower-case) vector in "peigencalc.hpp" and "superpose3d.hpp" with "std::vector?  If it helps, one quick way to do this is to use sed:
```
sed -i 's/vector</std::vector</' peigencalc.hpp
sed -i 's/std::vector<vector/std::vector<std::vector/' peigencalc.hpp
sed -i 's/vector</std::vector</' superpose3d.hpp
sed -i 's/std::vector<vector/std::vector<std::vector/' superpose3d.hpp
```
Do you still get the same compiler error?
-Andrew

**Comment by jewettaij** [comment]
I see what the problem is.  My test_superpose3d.cpp test code contains the line "using namespace std;".  When I remove that line, I get the same error you get.  I should not assume that people will enable namespace std by default.  I will update peigencalc.hpp so that it uses "std::vector".

Thanks for reporting this.
-Andrew

**Comment by jewettaij** [comment]
Try updating superpose_cpp to the [latest version](https://github.com/jewettaij/superpose3d_cpp/releases/tag/v1.1.3) with "git pull" (or re-clone it).  Does this fix the issue?

**Comment by KeeganBruer** [comment]
Yeah. That fixes the issue. thank you for helping.

**Comment by jewettaij** [comment]
Thank you.
